import React from "react";
import {MapContainer,TileLayer,Marker,Polyline,Popup} from "react-leaflet";
import {createFleetIcon} from "../../../components/maps/mapUtils";

function MiniMapPreview({route,height=200}){
if(!route)return null;
const center=[(route.depot.lat+route.bins[route.bins.length-1].lat)/2,(route.depot.lng+route.bins[route.bins.length-1].lng)/2];
return(<MapContainer center={center} zoom={14} style={{height,width:"100%",borderRadius:12,overflow:"hidden"}} zoomControl={false}><TileLayer url="https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}" maxZoom={20}/><Marker position={[route.depot.lat,route.depot.lng]} icon={createFleetIcon("depot")}><Popup>🏭 {route.depot.name}</Popup></Marker><Polyline positions={route.path} color={route.color} weight={5} opacity={0.9} lineCap="round" lineJoin="round"/>{route.bins.map(bin=>(<Marker key={bin.id} position={[bin.lat,bin.lng]} icon={createFleetIcon("bin",route.color)}><Popup>🗑️ {bin.name}</Popup></Marker>))}<Marker position={[route.bins[route.bins.length-1].lat,route.bins[route.bins.length-1].lng]} icon={createFleetIcon("end")}><Popup>🏁 {route.bins[route.bins.length-1].name}</Popup></Marker></MapContainer>);
}

function FleetDispatchModal({show,vehicle,routeData,selectedRoute,onSelectRoute,onConfirm,onClose,darkMode=true}){
if(!show||!vehicle)return null;
const routes=Object.keys(routeData);

return(<div className="modal-overlay" onClick={onClose}><div className="modal-content" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2><i className="fas fa-paper-plane"></i> Dispatch Vehicle</h2><button className="modal-close" onClick={onClose}>✕</button></div><div className="modal-body"><div className="dispatch-vehicle-info"><h3>{vehicle.vehicle_id} - {vehicle.driver_name}</h3><p>{vehicle.type} • {vehicle.location} • Fuel: {vehicle.fuel}%</p></div><p style={{color:darkMode?"#94a3b8":"#6b7280",marginBottom:16,fontSize:14}}><b style={{color:darkMode?"white":"#1e293b"}}>Select a route for dispatch:</b></p><div className="route-option-grid">{routes.map(routeKey=>{const route=routeData[routeKey];const isSelected=selectedRoute===routeKey;return(<div key={routeKey} className={`route-option ${isSelected?"selected":""}`} onClick={()=>onSelectRoute(routeKey)}><div className="route-option-header"><span className="route-option-name">{route.name}</span><div className="route-color-dot" style={{background:route.color}}></div></div><div className="route-option-meta"><span><i className="fas fa-ruler"></i> {route.distance} km</span><span><i className="fas fa-clock"></i> {route.time} min</span><span><i className="fas fa-trash"></i> {route.bins.length} bins</span></div><div className="route-option-bins"><div className="bins-label">Stops:</div><div className="bin-tags"><span className="depot-tag">{route.depot.name}</span>{route.bins.map(bin=>(<span key={bin.id} className="bin-tag">{bin.name}</span>))}</div></div>{isSelected&&(<div className="mini-map-container"><MiniMapPreview route={route} height={180}/></div>)}</div>);})}</div>{selectedRoute&&(<div className="route-details-preview"><h4><i className="fas fa-info-circle"></i> Route Summary</h4><div className="route-stats"><div className="route-stat"><div className="route-stat-icon">📏</div><div className="route-stat-value">{routeData[selectedRoute].distance}</div><div className="route-stat-label">KM</div></div><div className="route-stat"><div className="route-stat-icon">⏱️</div><div className="route-stat-value">{routeData[selectedRoute].time}</div><div className="route-stat-label">MIN</div></div><div className="route-stat"><div className="route-stat-icon">🗑️</div><div className="route-stat-value">{routeData[selectedRoute].bins.length}</div><div className="route-stat-label">STOPS</div></div><div className="route-stat"><div className="route-stat-icon">🏭</div><div className="route-stat-value">1</div><div className="route-stat-label">DEPOT</div></div></div></div>)}<div className="modal-actions"><button className="modal-btn secondary" onClick={onClose}>Cancel</button><button className="modal-btn primary" onClick={()=>onConfirm(selectedRoute)} disabled={!selectedRoute}><i className="fas fa-paper-plane"></i> Dispatch</button></div></div></div></div>);
}
export default FleetDispatchModal;